<template>
  <form @submit.prevent="saveMessage"> <!-- Use @submit.prevent on the form -->
    <div class="field">
      <label for="title">Title</label>
      <input type="text" id="title" v-model="message.title" /> <!-- Added ID for accessibility -->
    </div>
    <div class="field">
      <label for="messageText">Message</label>
      <textarea id="messageText" v-model="message.messageText"></textarea> <!-- Changed to textarea for multiline messages -->
    </div>
    <div class="actions">
      <button type="submit">Save Message</button>
      <button type="button" @click="cancel">Cancel</button> <!-- Added a cancel button -->
    </div>
  </form>
</template>

<script>
// REMOVE THIS IMPORT - No longer using external service
// import messageService from "@/services/MessageService.js";

import { mapActions } from 'vuex'; // Import mapActions

export default {
  name: "create-message",
  props: {
    // Ensure topicId is passed as a prop from your router config
    topicId: [Number, String]
  },
  data() {
    return {
      message: {
        // ID will be generated by the addMessage action in the store,
        // or you can generate it here:
        id: this.generateUniqueId(), // Use a method to generate ID
        topicId: this.topicId, // This prop should be correctly passed from the router
        title: "",
        messageText: ""
      }
    };
  },
  methods: {
    // Map the action to add a new message
    ...mapActions(['addMessage']), // This action is already defined in your store

    generateUniqueId() {
      // A simple method for unique IDs in a static context.
      // In a real app, IDs would come from the database.
      return Date.now() + Math.floor(Math.random() * 1000);
    },
    saveMessage() {
      if (!this.message.title.trim() || !this.message.messageText.trim()) { // Basic validation
        alert('Message title and text cannot be empty.');
        return;
      }

      // Ensure topicId is set before saving
      this.message.topicId = this.topicId;

      // Dispatch the Vuex action to add the new message to the store
      this.addMessage(this.message)
        .then(() => {
          // After successful addition, redirect to the messages for this topic
          this.$router.push({ name: "Messages", params: { topicId: this.topicId } }); // Use topicId
        })
        .catch(error => {
          console.error("Error adding message:", error);
          // Handle error, e.g., show an alert
        });
    },
    cancel() {
      // Go back to the previous page (topic details)
      this.$router.back();
    }
  },
  watch: {
    // If topicId can change while component is mounted (e.g., dynamic route changes)
    // ensure message.topicId is updated. Not strictly necessary if component remounts.
    topicId(newTopicId) {
      this.message.topicId = newTopicId;
    }
  }
};
</script>

<style>
/* Add some basic styles for the form, consistent with other forms */
form {
  margin-top: 20px;
  padding: 20px;
  background: rgba(255, 255, 255, 0.2);
  border-radius: 10px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.field {
  margin-bottom: 15px;
}

.field label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
  color: #333;
}

.field input[type="text"],
.field textarea { /* Added textarea style */
  width: 100%;
  padding: 10px;
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 5px;
  background: rgba(255, 255, 255, 0.8);
  box-sizing: border-box;
}

.field textarea {
  min-height: 100px; /* Give textarea a default height */
  resize: vertical; /* Allow vertical resizing */
}

.actions {
  text-align: right;
  margin-top: 20px;
}

.actions button {
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  font-size: 16px;
  margin-left: 10px;
}

.actions button[type="submit"] {
  background-color: #28a745; /* Green for save */
  color: white;
}

.actions button[type="submit"]:hover {
  background-color: #218838;
}

.actions button[type="button"] { /* For the Cancel button */
  background-color: #6c757d; /* Gray */
  color: white;
}

.actions button[type="button"]:hover {
  background-color: #5a6268;
}
</style>